services:

  db:
    image: postgres:17.6
    container_name: django-postgres
    restart: unless-stopped

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    env_file:
      - .env.prod

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  app:
    build: .
    container_name: django-app
    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    volumes:
      - static_data:/app/staticfiles
    env_file:
      - .env.prod


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile

    container_name: django-nginx
    restart: unless-stopped

    depends_on:
      - app

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - static_data:/static:ro


volumes:
  postgres_data:
  static_data: